name: JobClerk Scraper

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  scrape_jobs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Run Job Scraper
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python job_scraper.py
        
      - name: Commit state
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add seen_jobs.json
          git commit -m "Update seen jobs state" || echo "No new jobs to commit"
          git push

      - name: Keepalive Workflow
        run: |
          date > keepalive.txt
          git add keepalive.txt
          git commit -m "Keepalive commit" || echo "No keepalive needed"
          git push
